// src/components/flightbooking/mockData.js
export const airports = [
  {
    code: "JFK",
    name: "John F Kennedy International",
    city: "New York",
    country: "USA",
  },
  {
    code: "LAX",
    name: "Los Angeles International",
    city: "Los Angeles",
    country: "USA",
  },
  { code: "LHR", name: "Heathrow Airport", city: "London", country: "UK" },
  { code: "CDG", name: "Charles de Gaulle", city: "Paris", country: "France" },
  { code: "DXB", name: "Dubai International", city: "Dubai", country: "UAE" },
  { code: "HND", name: "Haneda Airport", city: "Tokyo", country: "Japan" },
  { code: "SYD", name: "Sydney Airport", city: "Sydney", country: "Australia" },
  {
    code: "FRA",
    name: "Frankfurt Airport",
    city: "Frankfurt",
    country: "Germany",
  },
  {
    code: "SIN",
    name: "Changi Airport",
    city: "Singapore",
    country: "Singapore",
  },
  {
    code: "ICN",
    name: "Incheon International",
    city: "Seoul",
    country: "South Korea",
  },
  {
    code: "ORD",
    name: "O'Hare International",
    city: "Chicago",
    country: "USA",
  },
  {
    code: "DFW",
    name: "Dallas/Fort Worth International",
    city: "Dallas",
    country: "USA",
  },
  { code: "MIA", name: "Miami International", city: "Miami", country: "USA" },
  {
    code: "MAD",
    name: "Adolfo Suárez Madrid–Barajas",
    city: "Madrid",
    country: "Spain",
  },
  {
    code: "AMS",
    name: "Amsterdam Airport Schiphol",
    city: "Amsterdam",
    country: "Netherlands",
  },
];

export const airlines = [
  { code: "EK", name: "Emirates", logoColor: "#D71921" },
  { code: "SQ", name: "Singapore Airlines", logoColor: "#004B87" },
  { code: "QF", name: "Qantas", logoColor: "#E40000" },
  { code: "CX", name: "Cathay Pacific", logoColor: "#EC1C24" },
  { code: "BA", name: "British Airways", logoColor: "#075AAA" },
  { code: "LH", name: "Lufthansa", logoColor: "#05164D" },
  { code: "AA", name: "American Airlines", logoColor: "#0078D2" },
  { code: "DL", name: "Delta Air Lines", logoColor: "#003366" },
  { code: "UA", name: "United Airlines", logoColor: "#024DA0" },
  { code: "TK", name: "Turkish Airlines", logoColor: "#C60C30" },
];

export const flights = [
  {
    id: "EK202",
    airline: "Emirates",
    airlineCode: "EK",
    flightNumber: "EK202",
    aircraft: "Airbus A380",
    departure: {
      code: "JFK",
      city: "New York",
      time: "08:30",
      date: "2024-06-15",
      terminal: "T4",
    },
    arrival: {
      code: "DXB",
      city: "Dubai",
      time: "19:45",
      date: "2024-06-16",
      terminal: "T3",
    },
    duration: "12h 15m",
    stops: 0,
    cabinClass: "Economy",
    baggage: {
      carryOn: { pieces: 1, weight: "7kg" },
      checked: { pieces: 2, weight: "23kg" },
    },
    price: {
      amount: 899,
      currency: "USD",
      taxes: 125,
      total: 1024,
    },
    amenities: ["WiFi", "Entertainment", "Meal", "USB Port", "Blanket"],
    isRefundable: true,
    isChangeable: true,
    seatAvailability: "Good",
  },
  {
    id: "SQ317",
    airline: "Singapore Airlines",
    airlineCode: "SQ",
    flightNumber: "SQ317",
    aircraft: "Boeing 777-300ER",
    departure: {
      code: "LHR",
      city: "London",
      time: "22:15",
      date: "2024-06-15",
      terminal: "T2",
    },
    arrival: {
      code: "SIN",
      city: "Singapore",
      time: "17:30",
      date: "2024-06-16",
      terminal: "T3",
    },
    duration: "13h 15m",
    stops: 0,
    cabinClass: "Economy",
    baggage: {
      carryOn: { pieces: 1, weight: "7kg" },
      checked: { pieces: 2, weight: "30kg" },
    },
    price: {
      amount: 1120,
      currency: "USD",
      taxes: 145,
      total: 1265,
    },
    amenities: ["WiFi", "Entertainment", "Meal", "Power Outlet", "Pillow"],
    isRefundable: true,
    isChangeable: false,
    seatAvailability: "Limited",
  },
  {
    id: "QF2",
    airline: "Qantas",
    airlineCode: "QF",
    flightNumber: "QF2",
    aircraft: "Boeing 787-9",
    departure: {
      code: "SYD",
      city: "Sydney",
      time: "16:20",
      date: "2024-06-15",
      terminal: "T1",
    },
    arrival: {
      code: "LAX",
      city: "Los Angeles",
      time: "12:30",
      date: "2024-06-15",
      terminal: "TBIT",
    },
    duration: "14h 10m",
    stops: 0,
    cabinClass: "Premium Economy",
    baggage: {
      carryOn: { pieces: 2, weight: "14kg" },
      checked: { pieces: 3, weight: "32kg" },
    },
    price: {
      amount: 1650,
      currency: "USD",
      taxes: 185,
      total: 1835,
    },
    amenities: [
      "WiFi",
      "Premium Meal",
      "Extra Legroom",
      "Priority Boarding",
      "Amenity Kit",
    ],
    isRefundable: false,
    isChangeable: true,
    seatAvailability: "Good",
  },
  {
    id: "BA178",
    airline: "British Airways",
    airlineCode: "BA",
    flightNumber: "BA178",
    aircraft: "Airbus A350-1000",
    departure: {
      code: "JFK",
      city: "New York",
      time: "18:45",
      date: "2024-06-15",
      terminal: "T7",
    },
    arrival: {
      code: "LHR",
      city: "London",
      time: "06:30",
      date: "2024-06-16",
      terminal: "T5",
    },
    duration: "6h 45m",
    stops: 0,
    cabinClass: "Business",
    baggage: {
      carryOn: { pieces: 2, weight: "12kg" },
      checked: { pieces: 3, weight: "32kg" },
    },
    price: {
      amount: 2450,
      currency: "USD",
      taxes: 225,
      total: 2675,
    },
    amenities: [
      "Lie-flat Bed",
      "Premium Dining",
      "Lounge Access",
      "WiFi",
      "Amenity Kit",
    ],
    isRefundable: true,
    isChangeable: true,
    seatAvailability: "Available",
  },
  {
    id: "LH403",
    airline: "Lufthansa",
    airlineCode: "LH",
    flightNumber: "LH403",
    aircraft: "Airbus A330-300",
    departure: {
      code: "FRA",
      city: "Frankfurt",
      time: "10:00",
      date: "2024-06-15",
      terminal: "T1",
    },
    arrival: {
      code: "JFK",
      city: "New York",
      time: "12:45",
      date: "2024-06-15",
      terminal: "T1",
    },
    duration: "8h 45m",
    stops: 0,
    cabinClass: "Economy",
    baggage: {
      carryOn: { pieces: 1, weight: "8kg" },
      checked: { pieces: 1, weight: "23kg" },
    },
    price: {
      amount: 750,
      currency: "USD",
      taxes: 115,
      total: 865,
    },
    amenities: ["WiFi", "Entertainment", "Meal", "Blanket"],
    isRefundable: false,
    isChangeable: false,
    seatAvailability: "Limited",
  },
  {
    id: "AA100",
    airline: "American Airlines",
    airlineCode: "AA",
    flightNumber: "AA100",
    aircraft: "Boeing 777-200",
    departure: {
      code: "LAX",
      city: "Los Angeles",
      time: "09:15",
      date: "2024-06-15",
      terminal: "T4",
    },
    arrival: {
      code: "HND",
      city: "Tokyo",
      time: "13:30",
      date: "2024-06-16",
      terminal: "T3",
    },
    duration: "11h 15m",
    stops: 1,
    stopDetails: [
      {
        airport: "SFO",
        duration: "2h",
        city: "San Francisco",
      },
    ],
    cabinClass: "Economy",
    baggage: {
      carryOn: { pieces: 1, weight: "7kg" },
      checked: { pieces: 2, weight: "23kg" },
    },
    price: {
      amount: 850,
      currency: "USD",
      taxes: 135,
      total: 985,
    },
    amenities: ["WiFi", "Entertainment", "Meal", "Power Outlet"],
    isRefundable: true,
    isChangeable: true,
    seatAvailability: "Good",
  },
];

export const popularDestinations = [
  {
    id: 1,
    city: "New York",
    country: "USA",
    code: "JFK",
    price: 499,
    image: "nyc",
  },
  {
    id: 2,
    city: "London",
    country: "UK",
    code: "LHR",
    price: 599,
    image: "london",
  },
  {
    id: 3,
    city: "Paris",
    country: "France",
    code: "CDG",
    price: 449,
    image: "paris",
  },
  {
    id: 4,
    city: "Tokyo",
    country: "Japan",
    code: "HND",
    price: 899,
    image: "tokyo",
  },
  {
    id: 5,
    city: "Dubai",
    country: "UAE",
    code: "DXB",
    price: 699,
    image: "dubai",
  },
  {
    id: 6,
    city: "Sydney",
    country: "Australia",
    code: "SYD",
    price: 1199,
    image: "sydney",
  },
  {
    id: 7,
    city: "Singapore",
    country: "Singapore",
    code: "SIN",
    price: 799,
    image: "singapore",
  },
  {
    id: 8,
    city: "Bangkok",
    country: "Thailand",
    code: "BKK",
    price: 649,
    image: "bangkok",
  },
];

export const cabinClasses = [
  { value: "economy", label: "Economy", description: "Standard seating" },
  {
    value: "premium",
    label: "Premium Economy",
    description: "Extra legroom & amenities",
  },
  {
    value: "business",
    label: "Business",
    description: "Premium service & seating",
  },
  { value: "first", label: "First Class", description: "Luxury experience" },
];

export const amenitiesList = [
  "WiFi",
  "Entertainment",
  "Meal",
  "USB Port",
  "Power Outlet",
  "Blanket",
  "Pillow",
  "Extra Legroom",
  "Priority Boarding",
  "Lounge Access",
  "Amenity Kit",
  "Premium Dining",
  "Lie-flat Bed",
];

export const countries = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "South Korea",
  "Singapore",
  "UAE",
  "Thailand",
  "China",
  "India",
  "Brazil",
  "Mexico",
  "Spain",
  "Italy",
  "Netherlands",
];
